### ISSUE TITLE
Import does not work

### ISSUE THREAD

**Issue by hhzl** [vicnet/benevoles#5]
Error message is

``function ( selector, context ) { // The jQuery object is actually just the init constructor 'enhanced' return new jQuery.fn.init( selector, context,``

**Comment by vicnet** [comment]
Just pull solution that was in local !

**Comment by hhzl** [comment]
https://github.com/vicnet/benevoles
does not have a ``local`` branch. 

May I ask you to just push a branch with the solution to your remote directory or update master and do a release?

**Comment by vicnet** [comment]
I use wrong words. I have update master with the solution.

**Comment by hhzl** [comment]
thank you fetching your commit from master https://github.com/vicnet/benevoles/commit/8f11263b6266ed67b28a179bcefd90036a05e325 made it work!

**Comment by vicnet** [comment]
Be carreful, when importing, Papaparse process empty lines so application try to use Benevole with nil field !
I have corrected it in last push.
